# ######################## xy_web_server配置 ###########################
# 默认配置文件位置为 当前工作目录下的 config/xy_web_server.toml


# ######################## xy_web_server项目配置 ###########################
[project]

# 项目名称, 仅支持英文
name = "xy_web_server_demo"

# 项目标识
identifier = "d38c56f5d3e348179c61d3ff31fc7487"

# 项目名称, 支持中英文
verbose_name = "xy_web_server_demo"

# 项目说明, 支持中英文
description = "xy_web_server_demo"

# 项目路径
path = "/mnt/bs-media/Workspace/project/opensource/xy-web-service/xy_web_server/samples/xy_web_server_demo"

# ######################## xy_web_server运行配置 ###########################

[runner]

# 服务源码目录自动添加到sys.path
# 默认 当前项目目录下的 source/Runner
path = "../source/Runner"

# 服务入口类，根据上文的path寻找对应的类初始化即为启动，字符串，若包含模块使用module.class根据importlib引入
# 默认 Runner.Runner
runner = "Runner.Runner"
