# ######################## xy_work配置 ###########################
# 默认配置文件位置为 当前工作目录下的 config/xy_work.toml


# ######################## xy_work项目配置 ###########################
[xy_work_project]

# 项目名称, 仅支持英文
name = "test_web_server"

# 项目标识
identifier = "c23d17b3d8fa488f867093fed2fe2c36"

# 项目名称, 支持中英文
verbose_name = "test_web_server"

# 项目说明, 支持中英文
description = "test_web_server"

# 项目路径
path = "/mnt/bs-media/Workspace/project/opensource/xy-web-service/xy_web_server/samples/test_web_server"

# ######################## xy_work运行配置 ###########################

[xy_work_runner]

# 服务源码目录自动添加到sys.path 
# 默认 当前项目目录下的 source/Runner
path = "../source/Runner"

# 服务入口类，根据上文的path寻找对应的类初始化即为启动，字符串，若包含模块使用module.class根据importlib引入
# 默认 Runner.Runner
runner = "Runner.Runner"
