# Generated by Django 5.1.2 on 2024-10-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Demo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mdemo",
            options={"verbose_name": "样例", "verbose_name_plural": "样例"},
        ),
        migrations.AddField(
            model_name="mdemo",
            name="text",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="文本"
            ),
        ),
    ]
